#Docker Compose File
version: '3.9'
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        
        restart: on-failure    
networks:
    hostnet: {}        

