# Generated by Django 3.1.3 on 2021-02-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteams', '0002_auto_20210227_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='img',
            field=models.ImageField(upload_to='static'),
        ),
    ]
