# Generated by Django 3.1.3 on 2021-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteams', '0003_auto_20210227_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
