# Generated by Django 3.1.3 on 2021-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteams', '0004_auto_20210227_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='img',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
