# Generated by Django 3.1.3 on 2021-03-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourteams', '0006_ourgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ourteam',
        ),
    ]
