# Generated by Django 3.1.3 on 2021-03-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteams', '0013_auto_20210301_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourgallery',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
