# Generated by Django 3.1.3 on 2021-02-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourteams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ourteams',
            new_name='ourteam',
        ),
    ]
