# Generated by Django 3.1.3 on 2021-02-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteams', '0005_auto_20210227_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='static/media')),
            ],
        ),
    ]
